name: Deploy my site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Rsync the build
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          src: ${GITHUB_WORKSPACE}
          # Remote server and path. i.e user@server.com:/var/www/server.com/
          dest: ${{secrets.RSYNC_DEST}}
      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
